apiVersion: v1
kind: Service
metadata:
    name: db-cloud-svc
    namespace: db-cloud-k8s
spec:
    selector:
        app: db-cloud-k8s
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000